# Generated by Django 3.2.9 on 2021-11-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidform', '0002_alter_tempintofile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempinto',
            name='status',
            field=models.CharField(default='待处理', max_length=255, null=True),
        ),
    ]
