# Generated by Django 3.2.9 on 2021-11-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidform', '0003_tempinto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempinto',
            name='status',
            field=models.CharField(default='no', max_length=255, null=True),
        ),
    ]
