# Generated by Django 3.2.9 on 2021-11-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidform', '0004_alter_tempinto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempinto',
            name='status',
            field=models.CharField(default='待处理', max_length=255),
        ),
    ]
