# Generated by Django 3.2.9 on 2021-11-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidform', '0005_alter_tempinto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempinto',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempinto',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempinto',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
